name: memguard_core
description: "Memory security core: encrypted storage and Rust FFI helpers."
version: 2.1.4
homepage: https://github.com/cas8398/memguard_core
repository: https://github.com/cas8398/memguard_core
issue_tracker: https://github.com/cas8398/memguard_core/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flagodna.memguard
        pluginClass: MemGuardPlugin

  # Add this: tell Flutter to bundle the prebuilt .so on Linux
  assets:
    - lib/linux/libmemguard_ffi.so
