name: memguard_core
description: "Memory security core: encrypted storage and Rust FFI helpers."
version: 2.1.3
homepage: https://github.com/cas8398/memguard_core
repository: https://github.com/cas8398/memguard_core
issue_tracker: https://github.com/cas8398/memguard_core/issues
documentation: https://github.com/cas8398/memguard_core#readme

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0" # Add flutter constraint

flutter:
  plugin:
    platforms:
      android:
        package: com.flagodna.memguard
        pluginClass: MemGuardPlugin
